### ISSUE TITLE
Smart irrigation failed to setup after updating to latest version

### ISSUE THREAD

**Issue by wauswaus** [jeroenterheerdt/HAsmartirrigation#355]
### What happened?

Updated to version v2024.4.5

### How to reproduce

update?

### Relevant log output

```shell
Logs tell me this:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 551, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smart_irrigation/__init__.py", line 102, in async_setup_entry
    if hass.data[const.DOMAIN][const.CONF_OWM_API_VERSION] == "2.5":
       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'owm_api_version'
```

### Which version are you running?

v2024.4.5

### Diagnostics file

- [X] I have attached a diagnostics file

### Additional information

Can't attacht diagnostics file as it is not available when integration is not setup

**Comment by wauswaus** [comment]
Now saw that I still has 'show beta versions' ticked in HACS... so this issue is not in a released version

**Comment by jeroenterheerdt** [comment]
Thanks, were you using OWM before? If so, which api version?

**Comment by wauswaus** [comment]
I do not use OWM at all

**Comment by Smittybk1** [comment]
I have the same issue. Here is my log output
Logger: homeassistant.config_entries
Source: config_entries.py:575
First occurred: 6:30:29 PM (1 occurrences)
Last logged: 6:30:29 PM

Error setting up entry Smart Irrigation for smart_irrigation
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 575, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smart_irrigation/__init__.py", line 96, in async_setup_entry
    ).strip()
      ^^^^^
AttributeError: 'NoneType' object has no attribute 'strip'

**Comment by DanDan800** [comment]
Same here. I use API 3.0 of OWM quire a while. Installation broke after updating to 2024.4.5

Logger: homeassistant.config_entries
Quelle: config_entries.py:575
Erstmals aufgetreten: 10:25:49 (1 Vorkommnisse)
Zuletzt protokolliert: 10:25:49

Error setting up entry Smart Irrigation for smart_irrigation
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 575, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smart_irrigation/__init__.py", line 72, in async_setup_entry
    store = await async_get_registry(hass)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smart_irrigation/store.py", line 645, in async_get_registry
    return cast(SmartIrrigationStorage, await task)
                                        ^^^^^^^^^^
voluptuous.error.MultipleInvalid: expected SOLRAD_behavior or one of '1', '2', '3' for dictionary value @ data['solrad_behavior']

**Comment by jeroenterheerdt** [comment]
> Same here. I use API 3.0 of OWM quite a while. Installation broke after updating to 2024.4.5
> 
> Logger: homeassistant.config_entries Quelle: config_entries.py:575 Erstmals aufgetreten: 10:25:49 (1 Vorkommnisse) Zuletzt protokolliert: 10:25:49
> 
> Error setting up entry Smart Irrigation for smart_irrigation Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/config_entries.py", line 575, in async_setup result = await component.async_setup_entry(hass, self) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/smart_irrigation/**init**.py", line 72, in async_setup_entry store = await async_get_registry(hass) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/smart_irrigation/store.py", line 645, in async_get_registry return cast(SmartIrrigationStorage, await task) ^^^^^^^^^^ voluptuous.error.MultipleInvalid: expected SOLRAD_behavior or one of '1', '2', '3' for dictionary value @ data['solrad_behavior']

This is not the same issue at all, please open a separate issue for this.

**Comment by jeroenterheerdt** [comment]
please try https://github.com/jeroenterheerdt/HAsmartirrigation/releases/tag/v2024.5.0

**Comment by wauswaus** [comment]
Latest beta seems to fixed it

**Comment by Smittybk1** [comment]
Dumb question....how can I use the above link for the fix and add it to HA? I see the zip file. How do I use it?

**Comment by jeroenterheerdt** [comment]
Install beta version through HACS.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by wauswaus** [comment]
> Dumb question....how can I use the above link for the fix and add it to HA? I see the zip file. How do I use it?

in HACS navigate to the Smart Irrigation page, then on the 3 vertical dots in the right upper corner select 'redownload'. On the screen thats opens select 'show beta versions' and then you can select the latest beta.

**Comment by Smittybk1** [comment]
Thank you! I'm all set and it's working
