### ISSUE TITLE
Can't get OWM with Smart Irrigation to work

### ISSUE THREAD

**Issue by domischnick** [jeroenterheerdt/HAsmartirrigation#406]
### What happened?

I tried to install SmartIrrigation over HACS with OWM. But it does not work for me

### How to reproduce

I installed and deinstalled several version of SmartIrrigation (2024.6.1 to 2024.6.8) OWM is crossed out in the sensors tab. I checked location, but its set up. Cause i get OWM with SmartIrrigation not to work, i used OWM HA module to get sensor values in SmartIrrigation 
![image](https://github.com/jeroenterheerdt/HAsmartirrigation/assets/115530511/6657d1ba-9881-4c00-b158-ca99e24c1f11)

I enabled debug, but cannot download an diagnostics file. if i click it nothing happend.

### Relevant log output

```shell
General log:

2024-06-11 11:23:42.786 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration smart_irrigation which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-06-11 11:23:42.788 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration landroid_cloud which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-06-11 11:23:42.789 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration homematicip_local which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-06-11 11:23:42.790 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-06-11 11:23:56.506 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'hacs' accesses hass.components.frontend. This is deprecated and will stop working in Home Assistant 2024.9, it should be updated to import functions used from frontend directly at custom_components/hacs/frontend.py, line 68: hass.components.frontend.async_register_built_in_panel(, please create a bug report at https://github.com/hacs/integration/issues
2024-06-11 11:23:56.605 WARNING (MainThread) [custom_components.smart_irrigation] Unable to find mapping with id in update all: 1
2024-06-11 11:24:02.261 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/config/custom_components/smart_irrigation/__init__.py", line 400, in async_sensor_state_changed
    if val.get(const.MAPPING_CONF_SENSOR) == entity:
       ^^^^^^^
AttributeError: 'str' object has no attribute 'get'
2024-06-11 11:24:02.267 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/config/custom_components/smart_irrigation/__init__.py", line 400, in async_sensor_state_changed
    if val.get(const.MAPPING_CONF_SENSOR) == entity:
       ^^^^^^^
AttributeError: 'str' object has no attribute 'get'
2024-06-11 11:24:02.269 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/config/custom_components/smart_irrigation/__init__.py", line 400, in async_sensor_state_changed
    if val.get(const.MAPPING_CONF_SENSOR) == entity:
       ^^^^^^^
AttributeError: 'str' object has no attribute 'get'
2024-06-11 11:24:02.275 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/config/custom_components/smart_irrigation/__init__.py", line 400, in async_sensor_state_changed
    if val.get(const.MAPPING_CONF_SENSOR) == entity:
       ^^^^^^^
AttributeError: 'str' object has no attribute 'get'
2024-06-11 11:24:02.277 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/config/custom_components/smart_irrigation/__init__.py", line 400, in async_sensor_state_changed
    if val.get(const.MAPPING_CONF_SENSOR) == entity:
       ^^^^^^^
AttributeError: 'str' object has no attribute 'get'
2024-06-11 11:24:02.279 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/config/custom_components/smart_irrigation/__init__.py", line 400, in async_sensor_state_changed
    if val.get(const.MAPPING_CONF_SENSOR) == entity:
       ^^^^^^^
AttributeError: 'str' object has no attribute 'get'
2024-06-11 11:24:26.152 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'hacs' accesses hass.helpers.event. This is deprecated and will stop working in Home Assistant 2024.11, it should be updated to import functions used from event directly at custom_components/hacs/base.py, line 630: self.hass.helpers.event.async_track_time_interval(, please create a bug report at https://github.com/hacs/integration/issues
2024-06-11 11:25:10.320 WARNING (Recorder) [homeassistant.components.sensor.recorder] The unit of sensor.openweathermap_rain (mm/h) cannot be converted to the unit of previously compiled statistics (mm). Generation of long term statistics will be suppressed unless the unit changes back to mm or a compatible unit. Go to https://my.home-assistant.io/redirect/developer_statistics to fix this
2024-06-11 11:25:10.321 WARNING (Recorder) [homeassistant.components.sensor.recorder] The unit of sensor.openweathermap_snow (mm/h) cannot be converted to the unit of previously compiled statistics (mm). Generation of long term statistics will be suppressed unless the unit changes back to mm or a compatible unit. Go to https://my.home-assistant.io/redirect/developer_statistics to fix this
2024-06-11 11:26:53.731 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to open inside the event loop by custom integration 'smart_irrigation' at custom_components/smart_irrigation/diagnostics.py, line 27: with open(storagefile) as f: (offender: /config/custom_components/smart_irrigation/diagnostics.py, line 27: with open(storagefile) as f:), please create a bug report at https://github.com/jeroenterheerdt/HASmartIrrigation/issues
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 672, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 639, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1988, in _run_once
    handle._run()
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 77, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 85, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware
    response = await handler(request)
  File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle
    result = await handler(request, **request.match_info)
  File "/usr/src/homeassistant/homeassistant/components/diagnostics/__init__.py", line 280, in get
    data = await info.config_entry_diagnostics(hass, config_entry)
  File "/config/custom_components/smart_irrigation/diagnostics.py", line 27, in async_get_config_entry_diagnostics
    with open(storagefile) as f:
```

### Which version are you running?

HASmartirigation 2024.6.8 HA 2024.6.1 with HAOS 12.3

### Diagnostics file

- [X] I have attached a diagnostics file

**Comment by domischnick** [comment]
if i deactivate debug. i can download a diagnostics file.
[home-assistant_smart_irrigation_2024-06-11T09-52-05.486Z.log](https://github.com/user-attachments/files/15785977/home-assistant_smart_irrigation_2024-06-11T09-52-05.486Z.log)

**Comment by domischnick** [comment]
i found the solution in a post before. I installed version 2024.1.0, configured everything and updated to 2024.6.1. Now OWM seems to work. Thanks for developing this nice piece of software

**Comment by jeroenterheerdt** [comment]
Which post are you referring to? It's weird that you don't get the download if debug is enabled. When you say 'debug is enabled' what exactly do you mean by the way?

**Comment by jeroenterheerdt** [comment]
> if i deactivate debug. i can download a diagnostics file. [home-assistant_smart_irrigation_2024-06-11T09-52-05.486Z.log](https://github.com/user-attachments/files/15785977/home-assistant_smart_irrigation_2024-06-11T09-52-05.486Z.log)

this is not a diagnostic file.

**Comment by jeroenterheerdt** [comment]
added extra validation for the error you reported even though I can't reproduce it. hope this helps.

**Comment by domischnick** [comment]
Found the solution on the end of issue #397: the guy installed also an old version and did a update afterwards to Version 2024.6.1. This works for me too. The difference with the old versions i had already a preset of zones, modules and sensors with newer versions I dont have this. Maybee this information helps. 
If i enable debug, and then  click on the 3 dots and download dignostics, nothing happens. if i click then deactivate debug, ican download the log file. (Now on 2024.6.1) .

**Comment by jeroenterheerdt** [comment]
> Hi! I am getting similar problem but slightly different error. In the gui I see also OWM as strikethrough: `Error doing job: Task exception was never retrieved Traceback (most recent call last): File "/config/custom_components/smart_irrigation/__init__.py", line 434, in _async_update_all ) = self.check_mapping_sources(mapping_id=mapping_id) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/smart_irrigation/__init__.py", line 1043, in check_mapping_sources for the_map in mapping[const.MAPPING_MAPPINGS].values(): ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^ TypeError: 'NoneType' object is not subscriptable`

please open a separate issue

**Comment by jeroenterheerdt** [comment]
closing as likely fixed in https://github.com/jeroenterheerdt/HAsmartirrigation/releases/tag/v2024.6.11. Feel free re-open create a new issue if not fixed.
