### ISSUE TITLE
Continuous updates bug

### ISSUE THREAD

**Issue by jeroenterheerdt** [jeroenterheerdt/HAsmartirrigation#570]
### Did you read the docs?

- [x] I read the docs and my question is not answered there.

### What happened?

```
025-06-07 09:10:46.763 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'smart_irrigation' sets option flow config_entry explicitly, which is deprecated at custom_components/smart_irrigation/options_flow.py, line 18: self.config_entry = config_entry. This will stop working in Home Assistant 2025.12, please create a bug report at https://github.com/jeroenterheerdt/HASmartIrrigation/issues 2025-06-07 09:11:16.882 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved (None) Traceback (most recent call last): File "/config/custom_components/smart_irrigation/__init__.py", line 467, in async_sensor_state_changed or val.get(const.MAPPING_CONF_SOURCE) ^^^^^^^ AttributeError: 'str' object has no attribute 'get' 2025-06-07 09:11:16.883 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved (None) Traceback (most recent call last): File "/config/custom_components/smart_irrigation/__init__.py", line 467, in async_sensor_state_changed or val.get(const.MAPPING_CONF_SOURCE) ^^^^^^^
```

### How to reproduce

see above

### Relevant log output

```shell

```

### Which version are you running?

not sure

### Diagnostics file

- [x] I have attached a diagnostics file

**Comment by jata1** [comment]
Not sure if related but I sometimes have a situation where the Smart irrigation side tab stops working. With lots of messages in the logs.

When this happens, I need to restart HA to get things back to normal. 

I am on 2025.6.b5

`2025-06-09 14:04:12.904 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140732595776352] Error handling message: Unknown error (unknown_error) Jago from 192.168.1.118 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 28, in _handle_async_response
    await func(hass, connection, msg)
  File "/config/custom_components/smart_irrigation/websockets.py", line 227, in websocket_get_config
    coordinator = hass.data[const.DOMAIN]["coordinator"]
                  ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
`
