### ISSUE TITLE
Zone calculation doesn't work in 2025.8.1

### ISSUE THREAD

**Issue by mission2010** [jeroenterheerdt/HAsmartirrigation#661]
### Did you read the docs?

- [x] I read the docs and my question is not answered there.

### What happened?

After updating to 2025.8.1 the button 'calculate all zones' has no effect. Even the scheduled calculation, doesn't update any values.

Related issue: https://github.com/jeroenterheerdt/HAsmartirrigation/issues/660

Please find the diagnostic logs attached.

[Report_6883566f970273001400a0e8.csv](https://github.com/user-attachments/files/21770495/Report_6883566f970273001400a0e8.csv)

### How to reproduce

click the 'calculate all zones' button. Nothing changes despite a full sunny day.

### Which version are you running?

2025.8.1

### Diagnostics file

- [x] I have attached a diagnostics file

**Comment by Denis198806** [comment]
I confirm, after updating to v2025.8.1, watering is not calculated, there are errors in the logs


```
Эта ошибка возникла в пользовательской интеграции.

Регистратор: homeassistant
Источник: custom_components/smart_irrigation/__init__.py:1624
интеграция: Smart Irrigation (документация, проблемы)
Зафиксировано первый раз: 14:00:12 (1 случай)
Зафиксировано последний раз: 14:00:12

Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/config/custom_components/smart_irrigation/__init__.py", line 843, in async_continuous_update_for_mapping
    await self.async_calculate_zone(
    ...<2 lines>...
    )
  File "/config/custom_components/smart_irrigation/__init__.py", line 1624, in async_calculate_zone
    if data.get(const.ATTR_DELETE_WEATHER_DATA, False):
       ^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by flintstones-fred** [comment]
I can confirm the behavior as well. 

However, if you go calculate individual zones, they get calculated as they should. I am not going to comment on the accuracy as I am still monitoring the precipitation values after making other changes I made. But I do see a number being calculated when I calculate individual zones. The “Calculate All Zones” is not doing anything.

**Comment by jeroenterheerdt** [comment]
Already fixed in 8.2beta. 8.2 will be released today
